### PR TITLE
update bundle ID for FDA in mobileconfig

### PR DESCRIPTION
**Pull request by apackel-huntress**

### CODE REVIEW

**Review by uttie-huntress — APPROVED** [review]
🚀

**Comment by uttie-huntress** [comment]
> 🚀
I rescinded the pr approval.

@evanburkeyhl pointed out about the PayloadUUIDs. The past ones were auto-generated by [Imazing Profile Editor](https://imazing.com/profile-editor), and the concern is that MDMs may use them to signify a change, which if true would make these moot.

I'd suggest to change it using that program, to be safe more than anything else since its unclear how these things work.

**Review by evanburkeyhl — APPROVED** [review]

**Comment by evanburkeyhl** [comment]
> > 🚀
> 
> I rescinded the pr approval.
> 
> @evanburkeyhl pointed out about the PayloadUUIDs. The past ones were auto-generated by [Imazing Profile Editor](https://imazing.com/profile-editor), and the concern is that MDMs may use them to signify a change, which if true would make these moot.
> 
> I'd suggest to change it using that program, to be safe more than anything else since its unclear how these things work.

Ah, I didnt see this before approving. Uttie raises a good point here.

**Comment by apackel-huntress** [comment]
I'm closing this. Someone more familiar with creating mobileconfigs and testing them should probably see this one through.

**Pull request closed without merging**
